# Mobb/Fortify Fixer on pull requests
# This workflow defines the needed steps to run Fortify on every pull request and pass the results to Mobb Fixer.
#
# Secrets in use (add your missing ones):
# FORTIFY_USER - your Fortify username
# FORTIFY_TENANT - your Fortify tenant name
# FORTIFY_API_TOKEN - your Fortify access token
# FORTIFY_RELEASE_ID - your Fortify app's release-id (number)
# MOBB_API_TOKEN - your mobb user credentials (autumatially set if you forked this repo via the Mobb app)
# GITHUB_TOKEN - automatically set by GitHub

name: "Mobb/Fortify"

on:
  pull_request:
    branches: ["*"]

jobs:
  scan-and-fix:
    name: Scan with Fortify and fix with Mobb
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    permissions:
      pull-requests: write
      statuses: write

    steps:
      - name: Setup Java on this machine
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "19"
      
      - name: Run Mobb on the findings and get fixes
        if: always()
        uses: mobb-dev/action/review@v1.1.1
        with:
          report-file: "scandata.fpr"
          api-key: ${{ secrets.MOBB_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          scanner: fortify
